<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <CWDir Condition=" '$(CWDir)' == '' ">E:\SteamLibrary\steamapps\common\Content Warning</CWDir>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="$(CWDir)\Content Warning_Data\Managed\*.dll" Private="false"/>
    </ItemGroup>

    <Target Name="CopyOutputFileToGame" AfterTargets="Build">
        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll;preview.png" DestinationFolder="$(CWDir)\Plugins\$(MSBuildProjectName)"/>
    </Target>

</Project>